#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail


# define tasks here
run () {
  current=${1}
  test_ > /dev/null && go run cmd/registry/main.go $current
}

build () {
  test_
  go build -o registry cmd/registry/main.go
}

test_ () {
  go test ./pkg/lib
  go test ./pkg/set1
  go test ./pkg/set2
}

list () {
  grep "() {" $0 | grep -v 'grep ' | awk '{print $1}' | sort
}

# main start here
command=${1:-""}

if [ -n "$(type -t $command)" ] && [ "$(type -t $command)" = function ]
then
  shift
  eval $command "$@"
  exit $?
fi

case "$command" in
  ls)
    list;;
  test)
    test_;;
  *)
    run
esac
